//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exception.ResourceMessageException", typeof(ResourceMessageException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo email não pode ser vazio.
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string INTERNAL_SERVER_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email em formato inválido.
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome não pode ser vazio.
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser vazia.
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa ter mais que seis caracteres.
        /// </summary>
        public static string PASSWORD_LESS_CHARACTERS {
            get {
                return ResourceManager.GetString("PASSWORD_LESS_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo de preparo é um enum.
        /// </summary>
        public static string RECIPE_COOKINGTIME_ISENUM {
            get {
                return ResourceManager.GetString("RECIPE_COOKINGTIME_ISENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dificuldade de preparo é um enum.
        /// </summary>
        public static string RECIPE_DIFFICULTY_ISENUM {
            get {
                return ResourceManager.GetString("RECIPE_DIFFICULTY_ISENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A receita precisa estar classificado em pelo menos um tipo de prato.
        /// </summary>
        public static string RECIPE_DISHTYPE_EMPTY {
            get {
                return ResourceManager.GetString("RECIPE_DISHTYPE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de prato é um enum.
        /// </summary>
        public static string RECIPE_DISHTYPE_ISENUM {
            get {
                return ResourceManager.GetString("RECIPE_DISHTYPE_ISENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A receita precisa conter pelo menos um ingrediente.
        /// </summary>
        public static string RECIPE_INGREDIENT_EMPTY {
            get {
                return ResourceManager.GetString("RECIPE_INGREDIENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível enviar um dos ingredientes como string vazia.
        /// </summary>
        public static string RECIPE_INGREDIENT_WITH_ONE_EMPTY {
            get {
                return ResourceManager.GetString("RECIPE_INGREDIENT_WITH_ONE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A receita precisa conter pelo menos uma instrução de preparo.
        /// </summary>
        public static string RECIPE_INSTRUCTION_EMPTY {
            get {
                return ResourceManager.GetString("RECIPE_INSTRUCTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A instrução da receita não pode começar com o passo zero..
        /// </summary>
        public static string RECIPE_INSTRUCTION_STEP_0 {
            get {
                return ResourceManager.GetString("RECIPE_INSTRUCTION_STEP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O passo da receita não pode ser repetido.
        /// </summary>
        public static string RECIPE_INSTRUCTION_STEP_REPEATED {
            get {
                return ResourceManager.GetString("RECIPE_INSTRUCTION_STEP_REPEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo sendo enviado vazio.
        /// </summary>
        public static string RECIPE_INSTRUCTION_TODO_EMPTY {
            get {
                return ResourceManager.GetString("RECIPE_INSTRUCTION_TODO_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título não pode ser vazio.
        /// </summary>
        public static string RECIPE_TITLE_EMPTY {
            get {
                return ResourceManager.GetString("RECIPE_TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User não autorizado.
        /// </summary>
        public static string UNAUTHORIZED_USER {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com este email.
        /// </summary>
        public static string USER_EMAIL_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("USER_EMAIL_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email e/ou senha inválidos.
        /// </summary>
        public static string USER_LOGIN_INVALID {
            get {
                return ResourceManager.GetString("USER_LOGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha antiga inválida.
        /// </summary>
        public static string USER_OLDPASSWORD_INVALID {
            get {
                return ResourceManager.GetString("USER_OLDPASSWORD_INVALID", resourceCulture);
            }
        }
    }
}
